name: Publish crates.io

on:
  push:
    # branches: [ main ]
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - '!v[0-9]+.[0-9]+.[0-9]+-*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
          toolchain: stable
    - uses: katyo/publish-crates@v2
      with:
          dry-run: false
          registry-token: ${{ secrets.CRATES_IO_ROCKET_GOVERNOR }}
